image:
  file: .gitpod.Dockerfile
tasks:
  - init: >
      cachix use aion-physics &&
      (yes | nix develop -c echo devShell build successful) &&
      bash -c "nix-store --export \$(nix-store --query -R --include-outputs \$(nix path-info --all)) > /workspace/nix_export"
  - command: >
      cachix use aion-physics &&
      bash -c "nix-store --import < /workspace/nix_export" &&
      (yes | nix develop -c echo devShell build import successful) &&
      direnv allow

vscode:
  extensions:
    - bbenoist.Nix
    - mkhl.direnv
