# Gitpod have promised to support devcontainers but it doesn't seem to work yet
# so we still need this file.
image:
    file: .gitpod.Dockerfile

vscode:
    extensions:
        - mkhl.direnv
        - ms-python.black-formatter
        - streetsidesoftware.code-spell-checker
        - editorconfig.editorconfig
        - mhutchie.git-graph
        - tamasfe.even-better-toml
        - donjayamanne.githistory
        - gitlab.gitlab-workflow
        - eamodio.gitlens
        - npxms.hide-gitignored
        - jnoortheen.nix-ide
        - ms-python.python
        - ms-python.debugpy
        - stkb.rewrap
        - gruntfuggly.todo-tree
